### ISSUE TITLE
Ch 4, table 4

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#11]
R57:
Suggest to make AccountingSupplierParty/Party/PartyIdentification/ID, AccountingSupplierParty/Party/PartyLegalEntity/CompanyID and AccountingSupplierParty/Party/EndpointID mandatory to have unik identification of the parties (and not only a name)

**Comment by SiwMeckelborg** [comment]
This should be discussed in next WG meeting, as a request for a restriction

**Comment by SiwMeckelborg** [comment]
Sellers Endpoint will be made mandatory, the rest of this request will be handled by national requirements

**Comment by SiwMeckelborg** [comment]
Add rule to ensure Sellers Endpoint ID is mandatory
