### ISSUE TITLE
Limiting ISO4217:2015

### ISSUE THREAD

**Issue by klakegg** [OpenPEPPOL/peppol-bis-invoice-3#13]
ISO4217:2015 contains codes for gold and silver, in addition to a large set of currencies not to be used within Europe. Should we limit the list to currencies used in Europe?

**Comment by SiwMeckelborg** [comment]
Should be discussed in next WG meeting

**Comment by MartinForsberg-Ecru** [comment]
The specification will be used by non-european companies. And also european suppliers may invoice in non-eu currencies.

**Comment by klakegg** [comment]
No problem about accepting non-european currencies, but do we need to accept gold as an currency?

**Comment by SiwMeckelborg** [comment]
Rejected
