### ISSUE TITLE
Mandatory invoice reference in Credit note

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#15]
With reference to prior comment (now closed)
I do not agree about the mandatory invoice reference from a credit note
And if this is a restriction to th EN I think it should be discussed like any other restriction - I do not recall this has been discussed in this context.

**Comment by SiwMeckelborg** [comment]
I have removed the requirement of a mandatory invoice reference, as this was text from the existing PEPPOL Billing profile, as stated in #4 

I might have misunderstood, do you want to have that restriction as part of the PEPPOL BIS?

**Comment by CSkovhus** [comment]
Ahh, sorry - thought it was my comment you "removed":-)
I'm very happy about the requirement beeing removed:-) so I will close this issue.
