### ISSUE TITLE
Taxes other than VAT

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#17]
In the EN (ch A.3.1) it is described how taxes other than VAT can be handled, and one option is to handle them as charges (on line or header level).
When this was decided in Dublin a code was pointed out from the codelist that could be used to identify a Tax from the different charges. I can't find any Tax codes in the referenced codelist now, and was wondering how to handle this in the PEPPOL BIS3?

**Comment by SiwMeckelborg** [comment]
Need further explanation
