### ISSUE TITLE
Profile doc, Table 1, Invoice type codes, Corrective invoice

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#23]
When reading the description of corrective invoices in the EN I'm not absolutely convinced that all receivers e.g. public authorities are actually able to handle these a “normal” invoice.
As I understand from the text “credit note or negative invoice may be sent with the difference in quantities and amounts between the correct invoice and the disputed invoice” allows the following scenario:
Original invoice:
1	Product 1, 10 PCE, 100 DKK
2	Product 2, 10 PCE, 200 DKK
3	Product 3, 10 PCE, 300 DKK
And then if they find out that the actually only needed 8 of product 2 and 12 of product 3, they can send an corrective Invoice with the difference e.g. 
2	Product 2, -2 PCE, -40 DKK
3	Product 3, 2 PCE, 60 DKK
Also if this is what is actually allowed it should be stated that in the corrective Invoice the definition of the “Invoice line identifier” changes from “A unique identifier for the individual line within the Invoice” to something like “A reference to the unique identifier for the individual line within the initial invoice”

**Comment by SLennartsson** [comment]
I agree, this is a problem. 
I initially interpreted 384 as a replacing complete invoice, with a invoice number identical to the number of the initial invoice, (this was based on the document name "corrected invoice, as opposed to "correcting invoice"), but EN16931-1 is very clear in that it mentions "a differential corrective invoice" in business process P10. 
In addition to problems with changing quantities and prices also other information elements may have to be corrected, or erased, by means of this invoice type. So please note that EN16931-1 explicitly mentions "lines that completely compensate lines in the disputed invoice" - such rules may have to be described in BIS 5A v3.
On top of all this : how do we distinguish a corrective 384 from a corrective 380, or a corrective 80, or a corrective 84? What are their respektive distinguishing characteristics?

**Comment by SiwMeckelborg** [comment]
Agree to leave out of profile 01 Billing
