### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#25]
We think it should be possible to specify the level of data protection in the invoice in accordance with the General Data Protection Regulation (GDPR).

A suggestion is to use AdditionalDocumentReference/ID for the GDPR level and AdditionalDocumentReference/DocumentDescription for "GDPR"

**Comment by SiwMeckelborg** [comment]
Reject the issue, it should be handled in the envelope/infrastructure
