### ISSUE TITLE
PaymentMeansCode

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#26]
We suggest to have the PaymentMeansCode list limited or at least specified which PaymentMeansCodes should be used in PEPPOL BIS3 for the PaymentMeans explicitly described in the EN (SEPA and Non-SEPA Direct Debit, SEPA and non-SEPA Bank transfer and Payment Card)
Suggestion for allowed PaymentMeansCodes:
1  	Instrument not defined
10 	Cash
31	Debit transfer
42	Payment to bank account
48	Bank card
49	Direct Debit
50	Payment by Postgiro
58	SEPA Credit transfer
59	SEPA Direct Debit
93	Reference giro
97	Clearing between partners 

(Fore some reason I can't access the BIS documents at "test-vefa.difi.no" right now, so I couldn't check if there are already examples of the used PaymentMeansCodes as in BIS5A)

**Comment by SiwMeckelborg** [comment]
The lates BIS document can be found here: 
https://test-vefa.difi.no/peppolbis/poacc/billing/3.0/bis/

**Comment by SiwMeckelborg** [comment]
Add subchapter to give further description of the payment means.

**Comment by apostolovski** [comment]
NL-CIUS Includes:
                                58           SEPA bankoverschrijving
                                59           SEPA incasso
                                57           Contractueel vastgelegd (verder niet gespecificeerd)
                                49           Incasso (niet-SEPA)
                                30           Bankoverschrijving (niet-SEPA)
                                48           Betaalkaart (Debit- of Creditcard)

**Comment by SiwMeckelborg** [comment]
I have added a description chapter for payment means:
https://test-vefa.difi.no/peppolbis/poacc/billing/3.0/bis/#_payment_means_information

Please review and report back any issues

**Comment by CSkovhus** [comment]
Looks good to me

**Comment by haf** [comment]
@SiwMeckelborg Your link is broken

**Comment by SiwMeckelborg** [comment]
Yes, this document has been moved into production environment, as this issue is from last December, and is closed. Updated BIS documents can be found here:  http://docs.peppol.eu/poacc/billing/3.0/
And details on payment means here: http://docs.peppol.eu/poacc/billing/3.0/bis/#_payment_means_information and codelist info here: http://docs.peppol.eu/poacc/billing/3.0/bis/#payment-means

**Comment by haf** [comment]
@SiwMeckelborg super!
