### ISSUE TITLE
Calculation rules for TaxTotal/TaxSubTotal

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#27]
BIS, Section 7.2
Calculation rules should be documented also for TaxTotal/TaxSubTotal.
As two occurrences of TaxTotal are possible on invoice/credit note level, some care is needed to express the rules correctly.

**Comment by SiwMeckelborg** [comment]
This is allready covered by the validation from TC434:

BR-CO-17: VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.

**Comment by klakegg** [comment]
Based on existing rules and documentation in EN, I don't understand what more is expected.

**Comment by SiwMeckelborg** [comment]
Suggest to add rule to prevent TaxSubtotal to be filled on the TaxTotal of the VAT currency

**Comment by SLennartsson** [comment]
The issue was raised when I realised that an e-invoice may contain up to two occurrencies of Invoice/TaxTotal. I now realise that my formulation of the issue was not as precise as it should have been. If I may illustrate with a couple of examples:
- For comparison, in our national format we have seen cases where implementors incorrectly recognise only “the second” occurrence of Invoice/TaxTotal in calculations and then interpret an omitted TaxSubTotal as value =0 
- Only the TaxTotal/TaxAmount in document currency may contribute to LegalMoneyTotal/TaxInclusiveAmount 

I believe Siw’s suggestion resolves my concern.

**Comment by klakegg** [comment]
To be solved in #35.
