### ISSUE TITLE
Improved reference to Unit of Measure 

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#28]
BIS, Section 8.1.15, Unit of measure
1. EN16931/BT-130 refers to UN/ECE rec 20 as well as UN/ECE rec 21, and the text goes on by saying that “Buyers only need to verify that the units used in the Invoice are equal to the units used in other documents” – a bold statement as directive 2006/112/EC lists “the quantity and nature of the goods supplied or the extent and nature of the services rendered” as mandatory information in invoices. 

2. The BIS refers to revision 8 (2012). Unfortunately I have not been able to locate that very version on https://www.unece.org/cefact/recommendations/rec_index.html 
Rec 20 version 8 is indeed listed there but it does not have the correct document linked to it. Where is the authoritative source document to be used in BIS 5A v3?

3. Generally the UN/ECE rec 20 is rather dysfunctional for the purpose of e-invoicing. Can something be done to improve or simplify its use? Questions to look at:

a) There is a process in UNCEFACT of moving packaging codes from Rec 20 to Rec 21. In that process “X code values” are specified in Rec 20 for the outgoing code values, for example “XDR=drum” in rec 20 is transferred to be “DR=drum” in rec 21. Can we agree on omitting “X code value”-series of rec 20?

b) When we refer to codes in rec 20 and rec 21 we need to recognize that the recommendations contain options for the codes. Can we agree that for BIS 5A v3 we use 
- “Common code“ as listed in annex II & III in case of Rec 20, and 
- “Code” in case of rec 21, as unitCode in BIS 5A v3?

c) Can we even contemplate a subset of the number of unit of measure?

d) A very common need for unit of measure is a generic concept for items/units/pieces. Unfortunately the recommendation contain many cryptic code alternatives in rec 20, for example: “H87=piece”, “C62=one”, “EA=each”, “E48=service unit”, “NAR=number of articles” (there may be more). Can we recommend the use of one of these as a generic unit of measure, as it may affect so many invoice receivers? 

e) Additionally, the stylesheet may have to address cryptic units of measure.

**Comment by SiwMeckelborg** [comment]
@klakegg, can you assess this?

**Comment by klakegg** [comment]
Use of Rec 20 and Rec 21 must be according to the EN where those are operationalized. I'm not sure what is expected of use in this issue.

**Comment by klakegg** [comment]
No feedback is received related to this issue. More concrete input must be provided as part of review process.
