### ISSUE TITLE
Code to indicate Intrastat classification

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#29]
BIS; Section 8.2.5 
With the introduction of the internal market the member states needed a new mechanism to collect trade statistics, as the statistics no more could be based on customs clearance data. Instead we got Intrastat, where traders monthly report their intracommunity flow of commodities to a governmental agency. 
When buying from other member states the traders commonly require their trading partners to give some statistical detail in the invoice, in addition to the country code a classification system called Combined Nomenclature appears to be used for this purpose (although I have seen other names, like "hs-number", "Customs-code", "CN.no", "Commodity code", "Tariff code", "Taric-code", "Tariff No"). In UNCL7153 potential options could be TSP, SRZ, HS or something else.

As this is of common use in EU, I’d suggest that the proper code value is clearly identified in BIS 5A v3.

**Comment by SiwMeckelborg** [comment]
My suggestion is to use the element Item classification identifier for this, as this element is repeatable. The scheme identifier for this is the UNTDID 7143, where there is a code= "HS":
Harmonised system
              The item number is part of, or is generated in the
              context of the Harmonised Commodity Description and
              Coding System (Harmonised System), as developed and
              maintained by the World Customs Organization (WCO).

I will add an example of this in chapter 9 of the BIS

**Comment by SLennartsson** [comment]
I am happy with any code value chosen. 
HS (Harmonised system) is a commonly used reference, but TSP (=EU Combined Nomenclature) and SRZ (Harmonized tariff schedule) are pretty strong options. [Again, this is an example that casts doubts over the UNCEFACT deliveries.]
Could the BIS document give some stronger message, than merely an example, to reduce the free choice of the invoice issuer?  For example, by adding a sentence next to your example to the effect of "Guidance for reporting of Intratat"?
