### ISSUE TITLE
Reference to an initial invoice

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#30]
BIS, Section 9.3 
A new sub-section is needed for to describe how a document (e.g. a credit note) should refer to an initial invoice to support the requirement of Directive 2006/112/EC, Article 219.

The primary option should be to list the invoice number of the initial invoice (or invoice numbers in case more than one is referenced).

But there are situations where it is impractical, or even impossible, to list the invoice numbers of all initial invoices concerned and in this case it should be acceptable to instead refer to the period under which the initial invoices were issued. Two examples may serve to illustrate situations where this second option can apply:
•	When crediting a rebate calculated on the sales volume over a specified period of time, in this case the rebate would apply to all invoices issued during that period. 
•	When there is a recurring supply/replenishment of a commodity it may not be possible to link any return of some of the items to a particular initial invoice; the same may apply also to returnable packaging.

**Comment by apostolovski** [comment]
FYI: NLCIUS’ standpoint on a negative invoice (or returns or volume discounts) where you cannot reference to one (or more) previously sent invoices, the new invoice should reference to the project, customer referrence (BT-10) or order (BT-13) where all invoices are related to.

**Comment by SiwMeckelborg** [comment]
@SLennartsson, would a solution/suggestion as NL is describing cover the needs?

**Comment by SLennartsson** [comment]
The wording of 2006/112/EC is ”… that amends and refers specifically and unambiguously to the initial invoice …”. The phrase leaves some room for exactly which piece of information is to be used as reference, but the seller has to make sure that the ambiguous reference exists in the correcting document. I believe that the reason for including the requirement in the directive is to provide the tax authorities with a means to secure that sellers produce complete and correct VAT details in their invoices.
 
Additionally, buyers may pose requirements of contractual/operational nature with regards to references when correcting documents are issued. Typically such references may be buyer reference (BT-10) or purchase order reference (BT-13). While these references are fully relevant to the buyer, I am not convinced that they can satisfy the directive’s requirement as well. Both BT-10 and BT-13 are defined by the buyer, and the seller cannot control or demonstrate how the buyer-issued reference links to the supplier’s initial invoice; the seller's auditor may have opinion on this. And above all, the tax authority auditor would be forced to go via the buyer’s system to verify seller’s tax compliance.

**Comment by SiwMeckelborg** [comment]
Add rule to make Preceding Invoice mandatory for all credit note types, as agreed in WG meeting
