### ISSUE TITLE
Consistent metod of healing with non-used conditional elements

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#31]
BIS, Section 9.3.1
I would oppose to introducing a “NA” (Not applicable) value in a conditional element as suggested. 
It is in no way better than sending “.” or “-“ values!
(Also it contradicts the text next to the exclamation mark immediately under 9.3.)

**Comment by SiwMeckelborg** [comment]
Agree
