### ISSUE TITLE
OriginatorDocumentReference

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#32]
BIS, Section 9.3.3
Can OriginatorDocumentReference be associated to a tender or lot through some further qualification?

In Sweden it is common to have an "originator document" of a different nature: an internal authorised document, called requisition (paper slip), is used as a basis for a purchase in a local shop or for collection of goods from a store. The transactions are semi-manual and commonly lower value but also these transactions are targeted for e-invoicing. By means of the requisition reference the e-invoice can be directed to the one authorising the requisition. (This assumes that there is a pre-arrangement with the shop or store).

**Comment by SiwMeckelborg** [comment]
Only the Tender or lot reference element exists in the EN, so no further qualifications are possible
