### ISSUE TITLE
Add a "format" attribut for binary objects?

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#33]
BIS, Section 6.2.10
A “format” attribute is needed for binary objects, or other wise a rule documented in som other way to show that BASE64 is to be used.

**Comment by SiwMeckelborg** [comment]
We cannot add an attribute, that would be an extension. @klakegg, is it an option to validate that the content is Base64?

**Comment by klakegg** [comment]
The CCTS type clearly states this to be an element containing Base64 content. I'm not aware of any way of inserting non-Base64 content into a CCTS BinaryObjectType. Please clarify, @SLennartsson.

**Comment by SLennartsson** [comment]
Skip the proposal to add a format attribute.
Great if there is rule on BASE64 objects only. But maybe there are more people than me that fail to penetrate the dokumentation down to CCTS type level. Would it be possible to highlight, somwhere in the BIS documentation, that binary objects are to be delalt with as BASE64 objects?

**Comment by SiwMeckelborg** [comment]
Added text in documentation:
https://test-vefa.difi.no/peppolbis/poacc/billing/3.0/ubl-invoice/structure/ubl-Invoice/cac-AdditionalDocumentReference/cac-Attachment/cbc-EmbeddedDocumentBinaryObject/
