### ISSUE TITLE
Line break in the text type

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#34]
BIS, section 6.2.9
It is good that line break is to be accepted character in text, but how to make sure it is not treated as whitespace? Maybe we should add a rule to the effect that “whitespace” should not be removed from the “text” data type?

**Comment by klakegg** [comment]
I'm not aware of any way to perform testing related to this as this is purely related to presentation on those systems where receiver actually use humans to look at the invoice. Please clarify, @SLennartsson.

**Comment by MartinForsberg-Ecru** [comment]
I don't think this should be implemented in the specification in the form of a validation rule. But rather as a highlight/notice informating the reader that linebreaks in text-fields should be preserved and respected by the receiver's system. See attached example.
[Linebreaks.zip](https://github.com/OpenPEPPOL/peppol-bis-invoice-3/files/1559940/Linebreaks.zip)
<img width="466" alt="presentation" src="https://user-images.githubusercontent.com/31277932/34002028-da20d47e-e0f1-11e7-8d1d-60c9a00ea8e5.png">

**Comment by SiwMeckelborg** [comment]
Added a notice in the chapter for data types/text as proposed by Martin.

**Comment by CSkovhus** [comment]
Ch 9.2.6: "And any line breaks should be preserved and respected by the receiver’s system."

To my knowledge preserving whitespaces is not standard XML behaviour - so I think it should be the senders responsible to wrap the text in CDATA-tags if the want the whitespaces preserved.

**Comment by SiwMeckelborg** [comment]
The text type is of data type "string", and according to 
https://www.w3.org/TR/xmlschema-2/#rf-whiteSpace
the default value of whiteSpace constraint is "preserve".
