### ISSUE TITLE
Variation rules for currencies and TaxTotal's

### ISSUE THREAD

**Issue by SLennartsson** [OpenPEPPOL/peppol-bis-invoice-3#35]
BIS, Section 13
If not already in place, I propose some validation rules 
1. For currencies, and 
2. For TaxTotal on invoice level 
to secure formal correctness of documents.

•	In a document, the values of DocumentCurrencyCode and TaxCurrencyCode (when both exist) may never be identical. 

•	In a document all /@currencyID = DocumentCurrencyCode, with the exception of “the second occurrence” of TaxTotal/TaxAmount (see below). This is clear from EN16931-3-1 document on the UBL syntax binding but it is not clear if it has materialised as a validation rule.

•	0..2 TaxTotal are allowed

•	If two occurrencies of TaxTotal exist in the instance, one of them 
a) must contain TaxAmount but no TaxSubTotal
b) must contain TaxAmount/@currencyID = TaxCurrencyCode

•	If just one TaxTotal exists in the instance, 
a) it must contain at least one TaxSubTotal
b) it must follow specified calculation & validation rules (see a separate comment to section 7.2).

**Comment by SiwMeckelborg** [comment]
* Rule PEPPOL-EN16931-R005, has allready been added to make sure TaxCurrency != DocumentCurrency
* Suggest to add rule to ensure all @currencyIDs = DocumentCurrencyCode except the one to indicate TaxTotal in local currency
* Add rule that only 2 instances of TaxTotal may exist
* Add rule to ensure "If two occurrencies of TaxTotal exist in the instance, one of them must contain TaxAmount but no TaxSubTotal"
* TaxSubtotal must exist only once and calculations are validated as well from the EN

**Comment by SiwMeckelborg** [comment]
rule text added
