### ISSUE TITLE
Ch. 9.5, AllowanceCharge

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#38]
In the examples the MultiplierFactorNumeric is specified as a "percent" e.g: 

```
<cbc:MultiplierFactorNumeric>2</cbc:MultiplierFactorNumeric>
<cbc:Amount currencyID="EUR">20</cbc:Amount> 
<cbc:BaseAmount currencyID="EUR">1000</cbc:BaseAmount>
```

I think it should be a "multiplier" e.g. 

```
<cbc:MultiplierFactorNumeric>0.02</cbc:MultiplierFactorNumeric>
<cbc:Amount currencyID="EUR">20</cbc:Amount> 
<cbc:BaseAmount currencyID="EUR">1000</cbc:BaseAmount>
```

That is also alligned with the suggestyed rule:
ID 8: BaseAmount * Multiplier = Amount for Allowance/Charge, if used.

(and UBL 2.1: "A number by which the base amount is multiplied to calculate the actual amount of this allowance or charge.")

**Comment by SiwMeckelborg** [comment]
In the EN, this element is specified as the percentage, so if an allowance percentage is 20%, the element must carry the value 20.  See explanation of the percentage type here: https://test-vefa.difi.no/peppolbis/poacc/billing/3.0/bis/#_percentage

I have also added a subchapter to explain the calculation of allowance and charge here: https://test-vefa.difi.no/peppolbis/poacc/billing/3.0/bis/#allowance-calc

**Comment by CSkovhus** [comment]
I agree that the it is specified as a percentage in EN, but from the definition of MultiplierFactorNumeric in UBL 2.1 I don't think that element is a percentage

**Comment by SiwMeckelborg** [comment]
In the syntax binding from EN, it is stated that the semantic meaning of the element differs from the semantic meaning of UBL, but is to be used as a percentage.

**Comment by CSkovhus** [comment]
Ok, couldn't find that - I will close
