### ISSUE TITLE
Create a PDF version of the BIS

### ISSUE THREAD

**Issue by phax** [OpenPEPPOL/peppol-bis-invoice-3#40]
The web version contains too much blank spaces when printed, so please provided a versioned PDF document. Thanks

**Comment by SiwMeckelborg** [comment]
CMB has been decided not to create pdf versions at this point

**Comment by phax** [comment]
Any why not? Unfortunately I could not attend the meeting on Wednesday :(

**Comment by phax** [comment]
Thanks for the swift response Siw. Would you be so kind and send me the date of the decision per mail (or post it here). I dislike this decision :)

**Comment by SiwMeckelborg** [comment]
9th of february 2018 :)

**Comment by phax** [comment]
I can't find anything on 2018-02-09 :) I was just agreed to continue with Asciidoc
On 2018-02-13 I find: 
> Philip recommends to also publish in PDF
So to me it is still open...

**Comment by SiwMeckelborg** [comment]
I will reopen and bring this up in the CMB again.

**Comment by phax** [comment]
Will do :)
