### ISSUE TITLE
Not subject to VAT invoices

### ISSUE THREAD

**Issue by SimonsPaul** [OpenPEPPOL/peppol-bis-invoice-3#45]
When creating an invoice from a non subject to VAT company, the schematron gives an error that VAT information is mandatory.

cac:TaxTotal 0..2 seems logic in the case of not subject to VAT companies.
 
On the other hand at line level 

cac:ClassifiedTaxCategory 1..1 makes VAT information mandatory and not logic from my point of view. Should be 0..1 in my opinion.

Extra info : This is not a problem in the current BIS.

A sample is attached.
[UBLBE_BE0000000196_V01-15000022_GitHub.zip](https://github.com/OpenPEPPOL/peppol-bis-invoice-3/files/1880159/UBLBE_BE0000000196_V01-15000022_GitHub.zip)

**Comment by SiwMeckelborg** [comment]
A non-VAT invoice shall have both TaxTotal and ClassifiedTaxCategory, but the category code should be set to "O" (the letter O for "Out of scope for VAT"

This is fully aligned with the cardinalities in EN16931. More information can be found here: http://docs.peppol.eu/poacc/billing/3.0/bis/#_value_added_tax_vat 

From TC434 an example file of invoices out of scope from VAT is found here:
https://github.com/CenPC434/validation/blob/master/ubl/examples/ubl-tc434-example7.xml

**Comment by SimonsPaul** [comment]
BT-48 says the percent should not be present at document level but if you ommit it at document level, you get an error.
Element/context: /Invoice/cac:TaxTotal/cac:TaxSubtotal
XPath test: (round(cac:TaxCategory/cbc:Percent) = 0 and (round(cbc:TaxAmount) = 0)) or (round(cac:TaxCategory/cbc:Percent) != 0 and (cbc:TaxAmount = round(cbc:TaxableAmount * (cac:TaxCategory/cbc:Percent div 100) * 10 * 10) div 100 ))
Error message: [BR-CO-17]-VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.
[UBLBE_BE0000000196_V01-15000022 (2).zip](https://github.com/OpenPEPPOL/peppol-bis-invoice-3/files/1883420/UBLBE_BE0000000196_V01-15000022.2.zip)

**Comment by SiwMeckelborg** [comment]
This is an issue with TC434 validation rules, not PEPPOL. I have reported this to Oriol, to fix this in the TC434 deliverables

**Comment by SiwMeckelborg** [comment]
The issue with BR-48 has been fixed by TC434, and the change is also now done for the PEPPOL BIS forked version of the TC434 rules. I therefore consider this case solved.
