### ISSUE TITLE
ICD6523 list

### ISSUE THREAD

**Issue by SimonsPaul** [OpenPEPPOL/peppol-bis-invoice-3#47]
I understood during the last meetings that we would (temporarily) continue to use the "99xx" numbers until registration was dealt with. The current schematron nevertheless raises a fatal error.

LegalEntity, TaxScheme, PartyIdentification, EndpointID.

Error message: [BR-CL-11]-Any registration identifier identification scheme identifier MUST be coded using one of the ISO 6523 ICD list.

Would it not be better to (temporarily) disable this test in order to be able to test sending/receiving invoices ?
Alternative is to test and neglecting these fatal errors but that is not the best/preferred way I presume.

Thanks in advance.

**Comment by SiwMeckelborg** [comment]
Hi, the choice to use the PEPPOL Party identifiers, are only for EndpointID, not other party identification schemes. Reason for using this for Endpoint, is that there exist no code list for the time being. For the other identifiers, the code list exist, and PEPPOL must follow these rules to be compliant.
