### ISSUE TITLE
Ch 2.3, first section

### ISSUE THREAD

**Issue by CSkovhus** [OpenPEPPOL/peppol-bis-invoice-3#5]
Reference to BIS 5.a

**Comment by SiwMeckelborg** [comment]
Can you please elaborate a bit more what is meant by this comment?

**Comment by CSkovhus** [comment]
I was just wondering if the reference should be to the new BIS and not the old one?

**Comment by SiwMeckelborg** [comment]
Is it this sentence: "The following chapters give an overview of the restricted set of codes that is used in this PEPPOL BIS."
 
This clearly says "this PEPPOL BIS" which is the new one?

**Comment by CSkovhus** [comment]
For some reason I do not have access to the BIS right now (https://test-vefa.difi.no/peppolbis/poacc/billing/3.0/) so I can't check - but maybe it has been changes since I made the comment, and in that case, the issue can be closed

**Comment by SiwMeckelborg** [comment]
Sorry, there has been an updated link to the CIUS:
https://test-vefa.difi.no/peppolbis/poacc/billing/3.0/cius/

**Comment by CSkovhus** [comment]
Thanks:-)
Copied from the BIS:
................
1.3. Benefits

The BIS 5a – Invoice and Credit note provides simple support for complex invoicing, where there is a need for credit note in addition to an invoice. Other potential benefits of using this BIS are, among others:
.................
Should it not be a reference to BIS3 (or what the name will be) instead of BIS 5a?

**Comment by SiwMeckelborg** [comment]
I will leave this issue open, untill we have the correct naming, and fix it then. Thanks!

**Comment by CSkovhus** [comment]
Ch deleted, issue no longer relevant
