### ISSUE TITLE
Probably wrong reference in BIS 3 spec

### ISSUE THREAD

**Issue by alarj** [OpenPEPPOL/peppol-bis-invoice-3#50]
Page http://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-Delivery/cbc-ActualDeliveryDate/
referes to Business term **BT-63**
As the UBL element itself is cbc:ActualDeliveryDate the right reference could be **BT-72** (based on description in CEN/TS 16931-3-2:2017) ?

**Comment by SiwMeckelborg** [comment]
Thanks for reporting this, this is fixed and available in test here:
http://test-docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-Delivery/cbc-ActualDeliveryDate/

I will leave the issue open until this has been updated in prod.
