### ISSUE TITLE
Allowance reason codes listed in PEPPOL BIS 3 text mismatch with validation artefacts

### ISSUE THREAD

**Issue by edmundgray** [OpenPEPPOL/peppol-bis-invoice-3#51]
The PEPPOL bis 3.0 specification has a section in the codelists for allowance reason codes (section 11.1.6).

The text in section 11.1.6 says “Any allowance reason codes shall be from UN/CEFACT code list 5189, D.16B”, clarifies that valid values are provided in the list in the guide (which is a restriction).

However, the validation artefacts list all the codes from the code list, including number 43, which isn’t defined in UN/CEFACT code list 5189, D.16B.

Can you please align the validation artefacts with the BIS 3 text?

**Comment by SiwMeckelborg** [comment]
I might misunderstand your issue, but the validation artefacts from PEPPOL adds a restriction (Enforced by rule PEPPOL-EN16931-CL002) to have the following codes allowed:

<let name="UNCL5189" value="tokenize('41 42 60 62 63 64 65 66 67 68 70 71 88 95 100 102 103 104 105', '\s')"/>

Which are the same as the ones listed in the BIS document.

The validation artefacts from TC434 however, allows all codes.

**Comment by carmenciciriello** [comment]
The issue is that PEPPOL seemed to have extended the codelist by including number 43, which is not present in the UN/CEFACT codelist.

**Comment by SiwMeckelborg** [comment]
43 is not on the list in the PEPPOL BIS: http://docs.peppol.eu/poacc/billing/3.0/bis/#_allowance_reason_codes
And not existing in the PEPPOL schematrons either:    
<let name="UNCL5189" value="tokenize('41 42 60 62 63 64 65 66 67 68 70 71 88 95 100 102 103 104 105', '\s')"/>

**Comment by sarafacchinetti** [comment]
I believe the 43 value is in the 5189 list of CEN schematron (https://github.com/CenPC434/validation/blob/master/ubl/schematron/codelist/EN16931-UBL-codes.sch ).
I added a comment to a UNTDID 5189 related issue (https://github.com/CenPC434/validation/issues/68)
