### ISSUE TITLE
 Card Payment and PrimaryAccountNumberID

### ISSUE THREAD

**Issue by alarj** [OpenPEPPOL/peppol-bis-invoice-3#52]
Hi,

currently Peppol BIS 3 spec (http://docs.peppol.eu/poacc/billing/3.0/bis/#_card_payment) refers

> If the Buyer had opted to pay by using a payment card such as a credit or debit card, information on the Primary Account Number (PAN) shall be present in the invoice.

and

> cbc:PrimaryAccountNumberID -- Mandatory, shall be the last **4 to 6** digits of the payment card number

At the same time the PCI DSS standard (https://www.pcisecuritystandards.org/documents/PCI%20SSC%20Quick%20Reference%20Guide.pdf) defines that only the **first six** and **last four** digits of the PAN may be printed.
There is a mismatch between different requirements?

**Comment by SiwMeckelborg** [comment]
This is an inheritance from EN16931, and not something we have decided in PEPPOL.  I have sent this information to TC434, and the response is that they do not see this as severe enough to issue a corrigendum to EN16931.
