### ISSUE TITLE
PEPPOL-EN16931-R040 calculation

### ISSUE THREAD

**Issue by sarafacchinetti** [OpenPEPPOL/peppol-bis-invoice-3#54]
Is this formula correct?

` test="not(cbc:MultiplierFactorNumeric and cbc:BaseAmount) or u:slack(if (cbc:Amount) then cbc:Amount else 0, (xs:decimal(cbc:BaseAmount) * xs:decimal(cbc:MultiplierFactorNumeric)) div 100, 0.02)"
              flag="fatal">Allowance/charge amount must equal base amount * percentage/100 if base amount and percentage exists</assert>`

The multiplierfactornumeric is already divided by 100

![image](https://user-images.githubusercontent.com/32299198/46071333-11003100-c180-11e8-8ab1-2dc3032c80f2.png)

The EN does not perform this check, just taking the allowance/charge amount. Is it really necessary to add a calculation rule here?

**Comment by sarafacchinetti** [comment]
Here an example how to use the MultiplierFactorNumeric
http://www.datypic.com/sc/ubl21/e-cac_Price.html 
![image](https://user-images.githubusercontent.com/32299198/46078321-149db300-c194-11e8-9d7b-1a10b423b421.png)

Please inform if this is correct

**Comment by MartinForsberg-Ecru** [comment]
The MultiplierFactorNumeric is mapped directly to the charge/allowance Percentage. 
The syntax binding from TC434 could perhaps also be clearer on this as it isn't a complete semantic match.

Take a look at the PEPPOL BIS 3 CIUS where an example is given:
http://docs.peppol.eu/poacc/billing/3.0/bis/#allowance-calc

**Comment by phax** [comment]
The documentation is pretty accurate here: `A number by which the base amount is multiplied to calculate the actual amount of this allowance or charge.` If I multiply with `20` I get the wrong result!

**Comment by sarafacchinetti** [comment]
> The MultiplierFactorNumeric is mapped directly to the charge/allowance Percentage.
> The syntax binding from TC434 could perhaps also be clearer on this as it isn't a complete semantic match.
> 
> Take a look at the PEPPOL BIS 3 CIUS where an example is given:
> http://docs.peppol.eu/poacc/billing/3.0/bis/#allowance-calc

If there is a  mismatch (SEM and SYN) a transformation logic should be highlighted in the EN 16931-3-2?  e.g the value of MultiplierFactorNumeric shall be multiplied by 100 in the UBL to CEN semantic model mapping. 
In my opinion the ubl should remain according to the ISO definition.
This means the Peppol example changes to:
  ```
  <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
    <cbc:AllowanceChargeReasonCode>CG</cbc:AllowanceChargeReasonCode>
    <cbc:AllowanceChargeReason>Cleaning</cbc:AllowanceChargeReason>
    <cbc:MultiplierFactorNumeric>0,20</cbc:MultiplierFactorNumeric>
    <cbc:Amount currencyID="EUR">200</cbc:Amount> 
    <cbc:BaseAmount currencyID="EUR">1000</cbc:BaseAmount>
    <cac:TaxCategory>
        <cbc:ID>S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
            <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
    </cac:TaxCategory>
</cac:AllowanceCharge>
```

**Comment by phax** [comment]
Of course it should be `<cbc:MultiplierFactorNumeric>0.20</cbc:MultiplierFactorNumeric>` :)

**Comment by sarafacchinetti** [comment]
sure, not comma...

**Comment by SiwMeckelborg** [comment]
This is a EN16931 issue, not a PEPPOL issue. EN16931 defines these elements as data type "Percentage", this has the following desctiption in chapter 6.5.5 "Percentages are given as fractions of a hundred (per cent) e.g. the value 34,78 % in percentage terms is given as 34,78. This EN 16931_ Percentage_ Numeric. Type is based on the Numeric. Type as defined in ISO 15000-5:2014, Annex B." The TC434 syntax description is mapping these elements to MultiplierFactorNumeric.

**Comment by SiwMeckelborg** [comment]
The business terms (example BT-94) are clearly marked as a semantic mismatch "SEM-2" in the syntax binding from TC 434. What we might do in PEPPOL is to give a very precise description, clearly stating that this is to be used by adding the value 20 for 20%.

**Comment by sarafacchinetti** [comment]
Sometime is SEM-2 and some is SYN-2. 
Anyhow this could represent a problem for Peppol BIS 3 as it adds restrictions on calculation which the EN didn't introduce for this reason: "Calculation within an Invoice line is not enforced in the validation to allow trade parties flexibility in rounding and multiplications of quantities and net prices"

**Comment by SiwMeckelborg** [comment]
Any comments regarding how TC434 has documented must be sent to CEN TC434, we have no possibility to do changes to the norm in PEPPOL.  
But, back to the issue in question here, PEPPOL WG for Billing decided to add validations to ensure correct calculations also on line level, but I do not quite see the relation between this issue and that rule, as if we changed the rule to not do the division by 100, e.g represent 20% as 0.2, we are still enforcing calculation. And the calculation on line level in PEPPOL allows for some slack, so calculations should validate OK even if you use a slightly different method of rounding.  If you want changes to these calculations, can I please ask you to send this as a change request to openPEPPOL PoACC here: https://openpeppol.atlassian.net/servicedesk/customer/portal/1

This GitHub issue site was used for the project, but as we now are in production and normal change request procedures are to be used, we ask that issues are sent as RfC's using the link above.

**Comment by sarafacchinetti** [comment]
Ok, thanks, you can close the issue.
